### ISSUE TITLE
virtualenvwrapper.sh not found

### ISSUE THREAD

**Issue by achichen** [carousell/laptop#6]
@victorneo, I got problem running this script

```
$ sh mac -dev
(ignored...)
mac: line 110: /usr/local/bin/virtualenvwrapper.sh: No such file or directory
```

The installation of `virtualenvwrapper` was removed in https://github.com/carousell/laptop/commit/7fe0e1605393a8ee0a167202c553fbfcb6b294a0#diff-140c1f12feeb2c52dfbeb2da6066a73a. It seems that `pip install virtualenvwrapper` is still required. Should we add it back?

BTW, my environment is even worse. The built-in python 2.7.10 on MacOS is not with `pip`. I need `sudo easy_install pip` it.

So here is what works for me:

```
sudo easy_install --upgrade pip
sudo pip install virtualenvwrapper
source "$HOMEBREW_PREFIX/bin/virtualenvwrapper.sh"
```

If it's okay, I'd make the PR.

**Comment by victorneo** [comment]
Hey Achi,

Please feel free to fix it and send the PR!

**Comment by achichen** [comment]
Got it, @victorneo !!
PR is created.
